### PR TITLE
Replit Bounty: Add github based Authentication

### PR DESCRIPTION
**Pull request by Shreyas-SAS**
Added Github based authentication as requested on Replit Bounties with 2 possible methods: 1. Direct Github login 2. Website based login & account page feature accessible via www.website.com/login and www.website.com/account pages.

Instructions to set up github auth as owner:
Step 1: SignIn to your github account on github.com
Step 2: click on your profile picure and go to the settings at the bottom of the list.
Step 3: Once you open the settings go down to the bottom and find developer settings option
Step 4: Click on OAuth Apps option and create a new application.
Step 5: in the application name add "next-auth" and in Homepage URL add http://localhost:3000 (should be replaced with URL on deployment) and in Authentication callback URL put http://localhost:3000/api/auth/callback/github
Step 6: click on register Application
Step 7: Copy the client ID and place it in the new .env file in front of GITHUB_ID=
Step 8: Now go back to github page and click on the "Generate a new client secret" button
Step 9: Copy this ID and paste it in front of GITHUB_SECRET=
Step 10: Also replace the hosted URL in front of NEXTAUTH_URL= if the website is hosted
Step 11: run the command "openssl rand -base64 32" on the terminal. If it does not work visit the website https://generate-secret.vercel.app/32
Step 12: copy the code generated and paste it in front of JWT_SECRET=
Step 13: you are now done with configuring the Github authentication with additional JWT based Auth Security.

In case of additional help needed with setup I am ready to assist you with that through a videocall. Thanks.

### CODE REVIEW

**Comment by Shreyas-SAS** [comment]
Adding referance to issue created: #15

**Comment by VulcanWM** [comment]
hey I'm sorry I can't merge this pull request since another user has already completed the bounty before you.
thanks for your effort, and i'm willing to tip 1000 cycles to any of your repls! just let me know which one you want me to tip.

**Comment by Shreyas-SAS** [comment]
> hey I'm sorry I can't merge this pull request since another user has already completed the bounty before you. thanks for your effort, and i'm willing to tip 1000 cycles to any of your repls! just let me know which one you want me to tip.

Oh thanks so much. Even if It wasn't accepted you can always use my code whenever needed. 
please tip the cycles on https://replit.com/@ShreyasSAS/ProjectZ if possible. Thanks.

btw, you can use the JWT check from my code, the one you accepted does not have the JWT check. its a better authentication and security measure over just plane Github Authentication. Also if you wish to make the check mandatory paste the line mentioned below at start of your index page and it will do the job. 

''' const {data:session} = useSession({required: true}) '''

paste it just after const { msg } = router.query and before return statement.

**Comment by Shreyas-SAS** [comment]
In case you have any such work please contact me at shreyassukhadeve@gmail.com, I can do the job at a much lesser cost than on Replit or Fiverr since Replit takes 25% comission. Best of luck for your future work.

**Comment by VulcanWM** [comment]
thanks! i'll try out the jwt code later.

**Comment by Shreyas-SAS** [comment]
> thanks! i'll try out the jwt code later.

thanks. I received the tip. IF you face any issue with the implementation feel free to ping me any time.

**Pull request closed without merging**
