### PR TITLE
[Replit Bounty] : added github OAuth

### PR DESCRIPTION
**Pull request by MadhuSaini22**
I've added Github Auth in this app :)

### CODE REVIEW

**Comment by MadhuSaini22** [comment]
@VulcanWM Deployment is failed because on vercel you need to set ENV variables. Once you'll set the env at vercel. Your app will be ready to use.

**Comment by VulcanWM** [comment]
hey I'm sorry I can't merge this pull request since another user has already completed the bounty before you.
thanks for your effort, and i'm willing to tip 500 cycles to any of your repls! just let me know which one you want me to tip.

**Comment by MadhuSaini22** [comment]
> hey I'm sorry I can't merge this pull request since another user has already completed the bounty before you. thanks for your effort, and i'm willing to tip 500 cycles to any of your repls! just let me know which one you want me to tip.

No problem, thanks for letting me know. I'm glad to hear that someone else was able to complete the bounty. I appreciate your offer to tip 500 cycles, that's very kind of you. I'd love to receive the tip on this [Repl](https://replit.com/bounties/@aidantorrence/create-a-nextjs-13-a?t=applications) project if that's okay. Thanks again!

**Comment by VulcanWM** [comment]
the link you provided wasn't a repl but a bounty...

**Comment by MadhuSaini22** [comment]
> the link you provided wasn't a repl but a bounty...

Oh yeah, I don't have any repl yet :l

**Pull request closed without merging**
