### PR TITLE
[Replit Bounty] Implemented GitHUB Login

### PR DESCRIPTION
**Pull request by anindosarker**
Hey, 
I saw your bounty ( #15 ) and as your description, I've implemented it and opened a PR

What you need to do?
Accept my bounty
And send me a message. I'll guide you through the next steps

### CODE REVIEW

**Comment by Shreyas-SAS** [comment]
> Hey, I saw your bounty ( #15 ) and as your description, I've implemented it and opened a PR
> 
> What you need to do? Accept my bounty And send me a message. I'll guide you through the next steps

Hey! @anindosarker I am really sorry to tell but actually I have nearly completed the bounty with a document file instructing her to set the Github credentials as an owner. Would it be possible if I complete it instead?
It is my first bounty so it would be great if you allow me to do so. Thanks.

**Comment by Shreyas-SAS** [comment]
> Hey, I saw your bounty ( #15 ) and as your description, I've implemented it and opened a PR
> 
> What you need to do? Accept my bounty And send me a message. I'll guide you through the next steps

I have also implemented a JWT control over what you have done. can I go ahead?

**Comment by VulcanWM** [comment]
Hey dude, this worked after I added a secret!
Can you apply to the bounty so I can accept you?

**Comment by anindosarker** [comment]
Yeah I already did. didn't you get the notification? @VulcanWM

**Pull request merged**
